# Javascript Node CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "JavaScript Linter"
          command: |
            mkdir -p reports/junit 
            npm run report-lint
      - run:
          name: "JavaScript Tests"
          command: |
            mkdir -p reports/junit 
            npm run report-junit
      - run:
          name: "JavaScript Coverage"
          command: |
            mkdir -p reports/junit 
            npm run report-coverage
      - codecov/upload:
          file: reports/lcov.info
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports
